### ISSUE TITLE
Improve usability on finish interview screen

### ISSUE THREAD

**Issue by katebanner** [complexdatacollective/Interviewer#1006]
While we want to maintain flexibility in terms of user choice to export, upload or delete sessions, a user suggested that it might be helpful to make the upload option more prominent.

Some additional background - this user wanted to make uploading automatic at the end of a session to improve clarity for and autonomy of the participant.

**Comment by wwqrd** [comment]
Would it be unreasonable to make 'upload and finish' the default option?

Something like:
![upload](https://user-images.githubusercontent.com/776599/70914519-0f828900-2010-11ea-8d58-8368479ee18d.png)

Another bit of simplification in this is to remove the delete on export option and instead:
- If the user 'uploads and finishes', or 'manually exports' and then finishes, just prompt to automatically delete: 'this interview has been exported and can be deleted (delete and finish) (keep and finish)'
- If the user does not upload or export, do not give the option to automatically delete it (they can still delete it manually in the sessions view)

**Comment by jthrilly** [comment]
Steve, I think what you have mocked up is along the lines of what we were thinking, except that it would be dependent on the client state. The reason the screen is the way it is now (with equal visual emphasis for export and upload) is that we weren't sure that the client would have a paired server and and be able to upload in any given moment.

The aim of this issue will be to redesign the start screen to intelligently use the client pairing state to visually emphasis _either_ upload or export.
