### ISSUE TITLE
Try to use 'isValid' to determine progress bar state on form interfaces

### ISSUE THREAD

**Issue by jthrilly** [complexdatacollective/Interviewer#1040]
It would be great if the progress bar at the bottom of form interfaces could be "smarter" about advising the user. In the screenshot below, the form is in an invalid state. We should tell the user: "It looks like you might have unanswered questions above. Answer them before clicking next."

<img width="888" alt="Screen Shot 2020-05-15 at 11 07 55 AM" src="https://user-images.githubusercontent.com/1387940/82039058-55657b00-969c-11ea-8e86-6f2c59cfc840.png">

**Comment by jthrilly** [comment]
Steve also suggested that the progress bar could show how many questions are left to answer, in cases where it isn't clear that there are items "below the fold".

Suggest "X of Y questions answered. Scroll to see more..."

**Comment by rebeccamadsen** [comment]
Not all the questions are going to be required. Should it still show X of Y questions answered? And some (like a toggle button) we won't necessarily know if it is "answered" or not because there is a default value. Also, an answered question may not be valid. Are we wanting to check validity at every change?

**Comment by jthrilly** [comment]
The user should always at least see the question, even if they are not required to answer it - its probably illogical to conflate "I didnt see this" with "I chose not to answer this". So to your question about if it should show X or Y questions answered when they arent required I think the answer is yes.

Toggles are a harder problem I agree. We could use visibility as a proxy here, but obviously that makes things complicated in terms of implementation, as we would need to track if a given element has been visible (might not be a bad idea in the long run).

In terms of this issue, the aim is really just to be more useful in the feedback we give in the progress bar. In other words:

- don't tell the user everything is okay to continue when it isn't
- advise them about issues in the form, including the fact there are questions below the fold.

If I were handling this issue an implementation might look like this:

- Use the scroll offset of the form container to tell if (1) the form is longer than the viewport, and (2) the user hasn't scrolled the form yet. If that is the case, show some text such as "Scroll to see more questions".
- When the progress bar is full, use the form `isValid` state to determine if the user is able to continue, or if there are invalid answers. Display this information next to the progress bar only at this point. We need to be a bit creative about triggering the validation as you say, so I would experiment with triggering it when the bottom of the screen is reached (progress bar is full) and see how it behaves.

**Comment by jthrilly** [comment]
Fixed in #1142
