### ISSUE TITLE
Revert changes to data export section filter and select

### ISSUE THREAD

**Issue by jthrilly** [complexdatacollective/Interviewer#1117]
https://github.com/complexdatacollective/Interviewer/issues/1104 Identified an issue in the interaction between the filter and the select toggle switches in the data export section. The issue was that when the filter was set, the select switches would select sessions that weren't visible to the user.

#1111 changed the behavior so that the filter is reset when the toggles are used. I wasn't paying close enough attention to this discussion and I want to revert this change.

The correct behavior is that the toggles should select from the visible list, which takes into account the filter. In other words, the filter should take precedence.

**Comment by wwqrd** [comment]
Yes that does make a lot more sense, I don't know what I was thinking there.
