### ISSUE TITLE
Import new version of a protocol failed even if the sessions are exported

### ISSUE THREAD

**Issue by lleleux** [complexdatacollective/Interviewer#1134]
Hi,

I try to import a new version of a protocol but it doesn't work. It tels that there are unexported sessions, But it's not true, you can see it just above the error message.

![Screenshot from 2021-05-25 14-56-03](https://user-images.githubusercontent.com/6029811/119502013-be7cd580-bd69-11eb-95e5-2e017a310fb6.png)

I tried on Linux and Android, with a file import or a server import, and it's always the same. Could you please let me know if I'm wrong with something ? 

Thank you very much !

Laurent

**Comment by lleleux** [comment]
Thanks for this very quick answer ;-)

**Comment by jthrilly** [comment]
We resolved this issue and have released 6.1.1 which contains a fix. Thanks again for your support of our software.
