### ISSUE TITLE
Interaction Logging

### ISSUE THREAD

**Issue by jthrilly** [complexdatacollective/Interviewer#178]
Mirroring the functionality we had previously, we will want to log meaningful user interactions within the app.

Previously, these were stored as an array of objects, along with nodes and edges (meaning the root data structure was `{ nodes: [], edges: [], log: [] }`). 

Meaningful interactions are particularly focused around navigation through the interview (timestamp when a stage is shown), and then interactions on the sociogram involving graph drawing. More detail to follow.

See also: #139

**Comment by wwqrd** [comment]
Implementation-wise we could potentially do this using rxjs to filter the redux event stream and output log events where appropriate.

**Comment by jthrilly** [comment]
Thats a really great suggestion, Steve.

**Comment by jthrilly** [comment]
Bernie has suggested we need to ensure that the first and second nodes nominated when alter linking is maintained.

**Comment by jthrilly** [comment]
This feature is under consideration for postponement.

**Comment by jthrilly** [comment]
Postponed until beta

**Comment by jthrilly** [comment]
This feature ultimately did not make it into the stable release due to time constraints. 

Given that implementation would be reasonably simple (as described above), and we do not currently have a use-case, this feature is postponed indefinitely.
