### ISSUE TITLE
Implement a property to indicate edge directionality should be preserved

### ISSUE THREAD

**Issue by jthrilly** [complexdatacollective/Interviewer#477]
We need a top level protocol property to indicate that edges should be created and managed in a directed fashion. That is A -> B != A <- B

- A new development protocol to test directed edges should be created in the example-protocols repo
- A boolean top level property `directedEdges` should be added this new protocol and set to true
- An issue should be created in Architect to implement the configurability of this parameter.
- Implementation of this should also update the wiki protocol page

**Comment by rebeccamadsen** [comment]
This should also check to see if we need to update any settings when exporting the graphML for directed edges. I believe gephi asks when I import a file if edges are directed or not, so it may not be a setting we need to set, but something users need to take care of themselves.

**Comment by jthrilly** [comment]
According to [this](http://graphml.graphdrawing.org/primer/graphml-primer.html), grapheml has a property to handle this at the root level:

  `<graph id="G" edgedefault="directed">`

This should also be implemented for this issue.

**Comment by jthrilly** [comment]
Closing, as implementation should happen as part of the broader feature (#183)
