### ISSUE TITLE
Ordinal Bin 2.0

### ISSUE THREAD

**Issue by jthrilly** [complexdatacollective/Interviewer#547]
- [ ] Animate when the number of bins changes. Ensure nodes animate out.
- [x] Prevent interaction with anything but the first node in the bucket
- [ ] Merge the bucket component with the nodeList.
- [x] Implement "interaction based sorting" in the OrdinalBins component. This will bypass sorting at the NodeList level.

**Comment by bryfox** [comment]
We may also want to look at the NodeList implementation here. If nodes don't change, the list doesn't update its state.

This makes sense on the NameGenerator, where we do want to re-use the panels between prompts. But in the dev protocol, for example, "Contact Frequency"/"Last six months" should not be the same as "Discussion Frequency"/"One". This is a minor issue, but I'd expect to see the animation even if nodes are the same in different buckets. (Currently, nothing happens, including updating scroll position.)
