### ISSUE TITLE
Review CSP settings

### ISSUE THREAD

**Issue by bryfox** [complexdatacollective/Interviewer#625]
We should restrict CSP to only what the app needs.

Currently, web workers also inherit the same CSP (see #613). As noted in #624, we'd ideally prevent those workers from making network requests to arbitrary URLs, but the app needs that functionality (at least some of the time...) in order to pair with Servers.

**Comment by bryfox** [comment]
In terms of web workers specifically, which prompted this issue, I think the potential threat is data exfiltration.

Workers are initialized with blobs, so inherit the CSP of the app itself. The app needs to load data from arbitrary URLs for the following:
- NC Server addresses (for pairing) are unknown in advance
- Import arbitrary protocols
- Import external data (coming later)

Workers have access to app data (the nodes being labeled, if nothing else). I don't see a way to prevent a compromised script from sending data across the network using CSP.

To mitigate, we should require https delivery of all protocols. This is enforced for paired server downloads, but should be required of URL-based downloads as well.

A further mitigation would be to not expose all external data (it currently isn't), unless there's a use case that actually requires it.

**Comment by bryfox** [comment]
I'll need to do more testing in places, but here's a first pass overview of the current CSP:

- `default-src gap://ready file://* blob:;`
    + `blob` required for agents that don't yet support worker-src (at least Safari right now)
    + Others can be moved to relevant sections; could add 'self' if needed
- `connect-src data: *;` (Network requests)
    + `data:`: ??
    + `*`: See worker notes above
        * Could require `https` in CSP, but that would mean accepting arbitrary certs during pairing
- `img-src asset: 'self' android-webview-video-poster: data: cdvfile: file:;`
    + `asset:`: used for protocol assets
    + `android-webview-video-poster:` needed for protocol assets
    + `data:`: for dev? Can remove with a webpack setting, I think (small sizes are inlined).
    + `cdvfile:`: ?? needed for phonegap?
    + `file:`: only for chrome dev?
- `media-src 'self' asset: cdvfile: file: data:;`
    + Should be able to mostly match img-src, but needs testing
- `style-src 'self' 'unsafe-inline'`;
    + `'unsafe-inline'` needed only for dev?
- `script-src 'self' 'unsafe-inline' 'unsafe-eval';`
    + `'unsafe-inline'`: not needed?
    + `'unsafe-eval'`: currently needed for wasm/libsodium
        * May be solved with wasm-eval in the future; in the meantime, we need to ensure ourselves that eval isn't called.
    + Like server, will need hash whitelist to support react-error-overlay
- `font-src 'self' data:;`
    + don't need `data`?
- `worker-src blob:;`
    + required

**Comment by jthrilly** [comment]
Closing as obsolete. In future many/most network requests will be handled by backend thread via limited public API. CSP can therefore be based on contemporary best practices with limited exceptions for specific functionality such as workers
