### ISSUE TITLE
Speed up protocol import on Cordova

### ISSUE THREAD

**Issue by bryfox** [complexdatacollective/Interviewer#702]
Follow-up issue from #692.

- Could be worth experimenting with increasing the buffer size to reduce write calls, but this increases memory use, so there would have to be some happy medium we derive from actual device testing.
  - currently using default size from JSZip
- Could theoretically rewrite zip extraction natively
- Could be a good place for a progress bar, and/or textual feedback like "Extracting {fileName.ext}..."

**Comment by jthrilly** [comment]
Relates to #881

**Comment by jthrilly** [comment]
Closing as obsolete. Future work will take place in capacitor.
