### ISSUE TITLE
On the roster name generator if the search box is open, delete icon is inaccessible

### ISSUE THREAD

**Issue by wwqrd** [complexdatacollective/Interviewer#735]
If the search box is open, when picking up an existing node, trash icon slides in beneath search box.

<img width="1324" alt="screen shot 2018-10-15 at 16 17 30" src="https://user-images.githubusercontent.com/776599/46960244-01487e00-d096-11e8-8cdd-a188927da247.png">

One possible fix might be to close the search box when clicking outside of it. Or perhaps nodes shouldn't be draggable on this screen?

**Comment by rebeccamadsen** [comment]
No longer applicable as of #1138
