### ISSUE TITLE
Enforce protocol schema & validations

### ISSUE THREAD

**Issue by bryfox** [complexdatacollective/Interviewer#785]
Once #774 is merged, we'll see console warnings for protocol validation failures.

If the level of validation seems OK, we can start to enforce the schema (e.g., display an error and refuse to open).

### Possible changes to validations (additions or removals)

- [x] bug: rule join type should not be required (default is AND)
- [x] bug: filter.rules should not be required
- [x] bug: allow `null` form prop in stage
- [x] bug: CardOptions.additionalProperties should not be required
- [x] bug: sort properties should allow the value '*' (not defined in properties)
- [x] bug: search options fuzziness should be optional
- [ ] enforce `binSortOrder` and `bucketSortOrder` refer to registered variables
- [ ] enforce fuzziness range (0-1 inclusive)

### Versioning

The schema is labeled as 'v1' for now. Eventually we'll need to decide on requirements and behavior for this (here and in Architect).

**Comment by jthrilly** [comment]
Use this as a meta issue for improvements to protocol validation

**Comment by jthrilly** [comment]
@wwqrd - thoughts on this? Did you want me to do something with it?

**Comment by wwqrd** [comment]
I think this might be out of date, going to have a look through these and check if already implemented:
- [ ] bug: sort properties should allow the value '*' (not defined in properties)
- [ ] bug: search options fuzziness should be optional
- [ ] enforce binSortOrder and bucketSortOrder refer to registered variables
- [ ] enforce fuzziness range (0-1 inclusive)

**Comment by wwqrd** [comment]
>  bug: search options fuzziness should be optional
It is in the schema validation, but not in architect

**Comment by wwqrd** [comment]
> bug: sort properties should allow the value '*' (not defined in properties)
Is allowed for sociogram, do we know where this was an issue?

**Comment by wwqrd** [comment]
Are the interface specific rules enforced? It seems like they may not be.

**Comment by jthrilly** [comment]
I think changing the schema now is not an option, so anything we need to do to support interface specific rules will need to happen in a new schema version, including an associated migration function. 

Based on that, I think we should hold on this for now.

**Comment by wwqrd** [comment]
Okay. Just to clarify, it seems like at least one rule that **already exist in the schema**, does not enforce anything.

Rule in the schema:
```
...
"SearchOptions": {
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "fuzziness": {
      "type": "number"
    },
    "matchProperties": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "fuzziness",
    "matchProperties"
  ],
  "title": "SearchOptions"
},
...
```

In protocol:
```
{
  ...
  "stages": [
    {
      ...
      "searchOptions": {
        "fuzziness": "ten",
        "foo": "bar",
      },
    },
  ],
}
```

The above protocol would still pass despite `fuzziness` being a string, `matchProperties` being undefined, and "foo" not being a valid property.
