### ISSUE TITLE
ADD_SESSION, SET_SESSION launch async actions but don't return them

### ISSUE THREAD

**Issue by wwqrd** [complexdatacollective/Interviewer#902]
ADD_SESSION, SET_SESSION actions launch workers asynchronously, but we don't return a promise from these actions. Meaning that we can't wait for them to complete.

This may be fine unless we need them for any following actions?

**Comment by jthrilly** [comment]
I think this should be no problem. The workers don't technically need to be ready for the session to start, but given that without them the interview would be weird, and we also want to expand this to include asset pre-rendering in the future. it makes sense to have a promise chain before session start that resolves with the session ID when everything is good to go.

**Comment by wwqrd** [comment]
This is implemented for addSession (for the preview feature), but not setSession yet. I think probably that change should be bundled with the pre-rendering feature rather than added speculatively now.
