### ISSUE TITLE
Large protocols may cause the app to crash during import on iOS.

### ISSUE THREAD

**Issue by wwqrd** [complexdatacollective/Interviewer#939]
Attempt to implement unzipping within a stream.

Another approach might be to use a web worker if it's actually hanging and not crashing.

Related: [Move to zip.js from JSZip? Or implement JSZip within webworker?](https://github.com/codaco/Network-Canvas/issues/881)

**Comment by wwqrd** [comment]
Some info from the related issue:
> We are emulating FileWriter streams on Cordova, which I think is a compromise based on what we could achieve with the API. The solution might be to find a Cordova zip plugin and handle it that way, it means forking the code, but we already had to do that for emulation.

**Comment by wwqrd** [comment]
https://github.com/MobileChromeApps/cordova-plugin-zip

**Comment by jthrilly** [comment]
> https://github.com/MobileChromeApps/cordova-plugin-zip

Looks to be abandoned, and with some issues, but perhaps worth looking for a maintained fork.

**Comment by wwqrd** [comment]
Looks like it may have been taken over by ionic enterprise? https://ionicframework.com/docs/native/zip

**Comment by jthrilly** [comment]
> Looks like it may have been taken over by ionic enterprise? https://ionicframework.com/docs/native/zip

I think that's just a plugin directory - it points back to the same GitHub repo.
