### ISSUE TITLE
App state migrations

### ISSUE THREAD

**Issue by wwqrd** [complexdatacollective/Interviewer#953]
Sometimes in order to add new features or fix bugs the app state will need to change shape. Since the app 'persists' state, this can lead to conflicts, where the app loads an out of date state that it can no longer use.

The library used to persist state has a migrations feature that can be used to solve this problem: https://github.com/rt2zz/redux-persist/blob/master/docs/migrations.md

Versions must be integers and are carried out in ascending order, so it is possible to jump several versions at once:
```js
const migrations = {
  0: (state) => {
    // migration clear out device state
    return {
      ...state,
      device: undefined   
    }
  },
  1: (state) => {
    // migration to keep only device state
    return {
      device: state.device
    }
  }
}
```

This update should be carried out across the full suite of apps:
- [ ] Network Canvas
- [ ] Server
- [ ] Architect

**Comment by jthrilly** [comment]
Closing, as no further development planned on Server.
